# See: https://pip.pypa.io/en/stable/topics/configuration/

[global]

; See: https://waylonwalker.com/pip-require-virtualenv/
require-virtualenv = True

; See: https://pip.pypa.io/en/latest/user_guide/#filtering-by-upload-time
uploaded-prior-to = P3D
