on: push
name: Mirror to GitLab
jobs:
  pushToGitLab:
    name: Push to GitLab
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Push to GitLab
      uses: spyoungtech/mirror-action@master
      env:
        GIT_USERNAME: artob
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      with:
        args: https://gitlab.com/artob/dotfiles.git
