alias git-push-all='git-push-github && git-push-rubyforge'
alias git-push-github='git push github master'
alias git-push-rubyforge='git push rubyforge master'
alias git-push-unfuddle='git push unfuddle master'
alias git-reset='git reset --hard'
alias git-ls='git log --pretty=oneline'
alias git-undo='git reset --soft HEAD^'
